### ISSUE TITLE
FileNotFoundError with bcftools log

### ISSUE THREAD

**Issue by mgalland** [YuSugihara/MutMap#10]
Dear Yu, 
Thank you for MutMap. I bumped into a weird mistake. My guess is that it is due to the split of the genome reference into chromosomes. Don't really know.  

This is my OS  `Linux x86_64 GNU/Linux` and my conda environment:
```bash
name: bsaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - mutmap = 2.3.2
  - snakemake = 5.20.0
  - fastp = 0.19.5
  - multiqc = 1.9
  - yaml = 0.2.5
  - snpeff = 5.0
  - parallel-fastq-dump = 0.6.7 
  - samtools = 1.14
  - bcftools = 1.14
```

Finally, here is the error message I got:

```bash
(bsaseq) bash-4.2$ mutmap --ref Oy-0DeNovo.fa -c D_Oy_0.final.sorted.bam  -b trimmed/bulk_R1_trimmed.fq.gz,trimmed/bulk_R2_trimmed.fq.gz        -n 51        --out run1/ -t 30
[MutMap:2021-11-22 17:20:16] start to run MutMap.
[MutMap:2021-11-22 17:20:16] maximum number of threads which you can use is up to 64.
[MutMap:2021-11-22 17:20:16] start to index reference fasta.
[MutMap:2021-11-22 17:21:39] indexing of reference successfully finished.
[MutMap:2021-11-22 17:21:39] start to align reads of bulk.0000 by BWA.
[MutMap:2021-11-22 17:41:24] alignment bulk.0000 successfully finished.
[MutMap:2021-11-22 17:41:24] start to merge BAMs.
[MutMap:2021-11-22 17:42:44] merging process successfully finished.
[MutMap:2021-11-22 17:42:44] start to call variants.
[MutMap:2021-11-22 17:42:45] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr5 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr5.vcf.gz >> run1//log/bcftools.Chr5.log 2>&1

please check below:

[MutMap:2021-11-22 17:42:45] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr2 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr2.vcf.gz >> run1//log/bcftools.Chr2.log 2>&1

please check below:

[MutMap:2021-11-22 17:42:45] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr4 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr4.vcf.gz >> run1//log/bcftools.Chr4.log 2>&1

please check below:

[MutMap:2021-11-22 17:42:45] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr3 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr3.vcf.gz >> run1//log/bcftools.Chr3.log 2>&1

please check below:

[MutMap:2021-11-22 17:42:45] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr1 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr1.vcf.gz >> run1//log/bcftools.Chr1.log 2>&1

please check below:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mpileup.py", line 139, in mpileup
    sbp.run(cmd1,
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r Chr5 -f run1//10_ref/Oy-0DeNovo.fa run1//20_bam/cultivar.bam run1//20_bam/bulk.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o run1//30_vcf/mutmap.Chr5.vcf.gz >> run1//log/bcftools.Chr5.log 2>&1' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mpileup.py", line 145, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/utils.py", line 19, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: 'run1//log/bcftools.log'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mgallan1/miniconda3/envs/bsaseq/bin/mutmap", line 10, in <module>
    sys.exit(main())
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mutmap.py", line 146, in main
    MutMap(args).run()
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mutmap.py", line 141, in run
    self.mpileup()
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mutmap.py", line 102, in mpileup
    mp.run()
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/site-packages/mutmap/mpileup.py", line 227, in run
    p.map(self.mpileup, chr_names)
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/mgallan1/miniconda3/envs/bsaseq/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'run1//log/bcftools.log'
```

Any clue why? 
Thank you in advance, 
Marc

**Comment by mgalland** [comment]
Ok, I think I figured out what caused the issue. 
In my `genome.fasta`, the headers were liked `>Chr1 (245904334)` with the chromosome length. This likely caused the problem with bcftools.   
I removed the extra part in the header to keep only `>Chr1` and it solved the issue. Hope this can help others. 
Cheers
Marc
