### ISSUE TITLE
Question about mutmap plot

### ISSUE THREAD

**Issue by highwire2021** [YuSugihara/MutMap#13]
Hi,
Many thanks to the developers.
I used use the mutmap v2.3.3  and showed "MutMap successfully finished". But the message "SystemError: tile cannot extend outside image" showed in the last line. I don't know how to deal with it. 
 
Could you help me?

Best wishes!

**Comment by YuSugihara** [comment]
Hi,

Would you share your VCF with the command line of QTL-seq that you used to run?

I added the new function from v2.3.3 to avoid a particular error.
Therefore, I'm a bit worried about if the error comes from the uptade.

**Comment by jcleydsonsilva** [comment]
Hello Sugihara.
I using the mutmap 2.3.4, and I had some errors. Please, I would be happy if you could help me. Will put some information about the error.
Thanks.
(bioinfo) xxxxxxx@pangenome:~/$ mutplot -v mutmap.vcf.gz -o NAMS_1_vs_FLNAMS_5_plot -n 20 -w 2000 -s 100 -f png --species Maize
[MutMap:2024-04-02 11:42:57] start to run MutPlot.
[MutMap:2024-04-02 11:42:57] output directory already exist.
!!WARNING!! Number of replicates for simulation is not enough to consider multiple testing correction. Therefore, the highest SNP-index and the second highest SNP-index were selected for p99 and p95, respectively.
[MutMap:2024-04-02 11:42:57] start to calculate SNP-index.
[MutMap:2024-04-02 11:44:25] SNP-index successfully finished.
[MutMap:2024-04-02 11:44:25] start to smooth SNP-index.
[MutMap:2024-04-02 11:44:25] smoothing process successfully finished.
[MutMap:2024-04-02 11:44:25] plotting now...
Traceback (most recent call last):
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/PIL/ImageFile.py", line 536, in _save
    fh = fp.fileno()
**AttributeError: '_idat' object has no attribute 'fileno'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/bin/mutplot", line 10, in <module>
    sys.exit(main())
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/mutmap/mutplot.py", line 191, in main
    mp.run()
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/mutmap/mutplot.py", line 180, in run
    pt.run()
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/mutmap/plot.py", line 164, in run
    plt.savefig('{}/mutmap_plot.{}'.format(self.out, self.args.format))
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1402, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/PIL/ImageFile.py", line 540, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/home/jferreiradasilva/anaconda3/envs/bioinfo/lib/python3.8/site-packages/PIL/ImageFile.py", line 551, in _encode_tile
    encoder.setimage(im.im, extents)
**SystemError: tile cannot extend outside image**

**Comment by ajfirl** [comment]
Hello, I have been getting this same error as well. But after some digging, the problem (at least in my case) is the error logs at the mutplot.py step, but it failed earlier during the SNP index calculations, with snpEff. It seems the bioconda install for mutmap uses an older version of java which is incompatible with the snpEff step.

For example, in the conda env for mutmap, running snpEff gives:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/snpeff/SnpEff has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

The java version in the conda environment is java 8.

If I deactivate the conda environment and run snpEff on its own, it runs fine, and the default java version is java 11. 

One solution would be to re-install mutmap from source and not use the bioconda recipe, just commenting here in case it is of use to the author. (Thank you for writing and maintaining this package!)

**Comment by YuSugihara** [comment]
Sorry for the late response.

I would like the VCF file which caused this error to fix the error.

I guess that this error comes from the plotting size because MutMap and QTL-seq dynamically calculate the plot size.

Can someone share the VCF?

**Comment by YuSugihara** [comment]
Also, although we implemented the multiple testing correction (--species) following the reviewer's comments, we do not recommend to use this option especially for the first time. You can run MutMap without using this option first and then you can add this option if you are interested in.

**Comment by YuSugihara** [comment]
Now the latest version is v2.3.7, and I hope this error has been fixed in this version.

**Comment by jcleydsonsilva** [comment]
Hi Yu,

Thank you for all your support. I'm working on new data, I let you know if I have any questions.

Best
Cleydson
________________________________
