### ISSUE TITLE
Mutplot error

### ISSUE THREAD

**Issue by Nikhilasai1223** [YuSugihara/MutMap#3]
i experienced this error when i am running Mutmap as well as Mutplot also  

Traceback (most recent call last):
  File "/home/priyanka/miniconda3/bin/mutplot", line 11, in <module>
    load_entry_point('mutmap', 'console_scripts', 'mutplot')()
  File "/home/priyanka/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/priyanka/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/priyanka/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2453, in load
    return self.resolve()
  File "/home/priyanka/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/priyanka/MutMap/mutmap/mutplot.py", line 12, in <module>
    from mutmap.plot import Plot
  File "/home/priyanka/MutMap/mutmap/plot.py", line 8, in <module>
    from qtlseq.utils import time_stamp
ModuleNotFoundError: No module named 'qtlseq'

**Comment by YuSugihara** [comment]
Dear Nikhilasai1223,

Sorry for my late response.
I checked your problem, and I found a bug related to your problem.

Thank you for your report.
I fixed it, and the new version (v2.2.0) will be available within a few days via bioconda.

If you would like to solve it as soon as possible,
Please clone this repository, and enter the copied directory.
After that, you can update MutMap by "pip install . " command by yourself.

If you cannot solve your problem using the new version,
please tell me.

Best regards,
Yu Sugihara
